[package]
name = "monoio-netreq"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
monoio = { version = "0.2.4", features = ["poll-io", "sync"] }
monoio-transports = "0.5.3"
monoio-http = "0.3.11"
http = "1.1.0"
thiserror = "1.0.65"
serde = "1.0.215"
serde_json = "1.0.132"
bytes = "1.8.0"
smol_str = "0.3.2"


[dev-dependencies]
anyhow = "1.0.92"
bytes = "1.8.0"


[features]
native-tls = ["monoio-transports/native-tls"]